version: '2'
services:
  redis:
    image: redis

  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - JWT_SECRETS=TEST,TEST2
     - DUPLICATE_STORAGE=memory
     - EVIDENCE_STORAGE=memory
     - STATUS_SERVICE=http://status.eventdata.crossref.org
     - EVENT_BUS_URL_BASE=https://bus.eventdata.crossref.org
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - DOI_CACHE_REDIS_PORT=6379
     - DOI_CACHE_REDIS_HOST=redis
     - DOI_CACHE_REDIS_DB=5
     - SKIP_DOI_CACHE=TRUE
    depends_on:
     - redis
    command: "lein test :unit"

