version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - JWT_SECRETS=TEST,TEST2
     - DUPLICATE_STORAGE=memory
     - EVIDENCE_STORAGE=memory
     - STATUS_SERVICE=http://status.eventdata.crossref.org
     - EVENT_BUS_URL_BASE=https://bus.eventdata.crossref.org
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - SKIP_DOI_CACHE=TRUE
     - SKIP_LANDING_PAGE_CACHE=TRUE
     - SKIP_ROBOTS_CACHE=TRUE
    command: "lein test :unit"

