version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ~/.m2-cache:/root/.m2
    environment:
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - PERCOLATOR_DUPLICATE_STORAGE=memory
     - PERCOLATOR_EVIDENCE_STORAGE=memory
     - GLOBAL_EVIDENCE_URL_BASE=https://evidence.eventdata.crossref.org
     - PERCOLATOR_SKIP_DOI_CACHE=TRUE
     - PERCOLATOR_SKIP_LANDING_PAGE_CACHE=TRUE
     - PERCOLATOR_SKIP_ROBOTS_CACHE=TRUE
    command: "lein test :unit"

