version: '2'
services:
  redis:
    image: redis

  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - PERCOLATOR_DUPLICATE_STORAGE=memory
     - PERCOLATOR_EVIDENCE_STORAGE=memory
     - PERCOLATOR_DOI_CACHE_REDIS_PORT=6379
     - PERCOLATOR_DOI_CACHE_REDIS_HOST=redis
     - PERCOLATOR_DOI_CACHE_REDIS_DB=5
     - PERCOLATOR_SKIP_DOI_CACHE=TRUE
     - PERCOLATOR_LANDING_PAGE_CACHE_REDIS_PORT=6379
     - PERCOLATOR_LANDING_PAGE_CACHE_REDIS_HOST=redis
     - PERCOLATOR_LANDING_PAGE_CACHE_REDIS_DB=6
     - PERCOLATOR_SKIP_LANDING_PAGE_CACHE=TRUE
     - PERCOLATOR_ROBOTS_CACHE_REDIS_PORT=6379
     - PERCOLATOR_ROBOTS_CACHE_REDIS_HOST=redis
     - PERCOLATOR_ROBOTS_CACHE_REDIS_DB=7
     - PERCOLATOR_SKIP_ROBOTS_CACHE=TRUE
     - GLOBAL_EVIDENCE_URL_BASE=https://evidence.eventdata.crossref.org
    depends_on:
     - redis
    command: "lein test :unit"

